"""
data.py
-------
This is our fake "database" for Phase 1. Everything lives in plain
Python data structures in memory:

    PRODUCTS -> a list of dicts, one per product. This is the catalog.
    CART     -> a dict of {product_id: quantity}. This is the (single, shared)
                shopping cart. There's no login system yet, so there is only
                ever one cart for the whole app.

The catalog is intentionally larger (48 products across 8 categories) and
carries a few extra fields -- brand, rating, reviews_count, tags -- that the
current UI doesn't display yet. They're here so a future recommendation
system ("customers who liked X also liked Y", tag/category-based
similarity, popularity-by-rating, etc.) has real data to work with without
another data-modelling pass later.

NOTE: Because this is all in memory, everything resets whenever the
FastAPI server restarts. That's expected for Phase 1 -- a real database
will replace this file in a later phase.
"""

PRODUCTS = [
    {
        "id": 1,
        "name": "AeroStride Runner",
        "description": "A lightweight running shoe built for daily trainer performance, featuring a mesh design runners can rely on mile after mile.",
        "price": 79.99,
        "category": "Running Shoes",
        "brand": "AeroStride",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=1",
        "stock": 25,
        "rating": 4.5,
        "reviews_count": 65,
        "tags": ["lightweight", "daily-trainer", "mesh"],
    },
    {
        "id": 2,
        "name": "TrailBlaze Trail Runner",
        "description": "A trail running shoe built for grip performance, featuring a off road design runners can rely on mile after mile.",
        "price": 94.5,
        "category": "Running Shoes",
        "brand": "TrailBlaze",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=2",
        "stock": 12,
        "rating": 4.0,
        "reviews_count": 118,
        "tags": ["trail", "grip", "off-road"],
    },
    {
        "id": 3,
        "name": "StrideCore Marathon Shoe",
        "description": "A marathon running shoe built for cushioned performance, featuring a long distance design runners can rely on mile after mile.",
        "price": 119.0,
        "category": "Running Shoes",
        "brand": "StrideCore",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=3",
        "stock": 8,
        "rating": 4.9,
        "reviews_count": 171,
        "tags": ["marathon", "cushioned", "long-distance"],
    },
    {
        "id": 4,
        "name": "PulseRun Speed Trainer",
        "description": "A speed running shoe built for racing performance, featuring a lightweight design runners can rely on mile after mile.",
        "price": 99.99,
        "category": "Running Shoes",
        "brand": "PulseRun",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=4",
        "stock": 17,
        "rating": 4.4,
        "reviews_count": 224,
        "tags": ["speed", "racing", "lightweight"],
    },
    {
        "id": 5,
        "name": "ZenPace Cushion Runner",
        "description": "A cushioned running shoe built for comfort performance, featuring a daily trainer design runners can rely on mile after mile.",
        "price": 84.99,
        "category": "Running Shoes",
        "brand": "ZenPace",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=5",
        "stock": 22,
        "rating": 3.9,
        "reviews_count": 277,
        "tags": ["cushioned", "comfort", "daily-trainer"],
    },
    {
        "id": 6,
        "name": "GripFlex Road Runner",
        "description": "A budget running shoe built for road performance, featuring a breathable design runners can rely on mile after mile.",
        "price": 69.99,
        "category": "Running Shoes",
        "brand": "GripFlex",
        "image": "https://loremflickr.com/400/400/running,sneakers?lock=6",
        "stock": 30,
        "rating": 4.8,
        "reviews_count": 330,
        "tags": ["budget", "road", "breathable"],
    },
    {
        "id": 7,
        "name": "SonicWave Over-Ear ANC",
        "description": "SonicWave's noise cancelling headphones deliver over ear sound with a wireless build made for everyday listening.",
        "price": 149.99,
        "category": "Headphones",
        "brand": "SonicWave",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=7",
        "stock": 18,
        "rating": 4.3,
        "reviews_count": 383,
        "tags": ["noise-cancelling", "over-ear", "wireless"],
    },
    {
        "id": 8,
        "name": "PulseBud True Wireless",
        "description": "PulseBud's earbuds headphones deliver compact sound with a bass build made for everyday listening.",
        "price": 59.99,
        "category": "Headphones",
        "brand": "PulseBud",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=8",
        "stock": 0,
        "rating": 3.8,
        "reviews_count": 436,
        "tags": ["earbuds", "compact", "bass"],
    },
    {
        "id": 9,
        "name": "EchoTone Studio Headphones",
        "description": "EchoTone's studio headphones deliver reference sound with a wired build made for everyday listening.",
        "price": 189.0,
        "category": "Headphones",
        "brand": "EchoTone",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=9",
        "stock": 6,
        "rating": 4.7,
        "reviews_count": 489,
        "tags": ["studio", "reference", "wired"],
    },
    {
        "id": 10,
        "name": "BassForge Bluetooth Buds",
        "description": "BassForge's earbuds headphones deliver budget sound with a bass build made for everyday listening.",
        "price": 44.99,
        "category": "Headphones",
        "brand": "BassForge",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=10",
        "stock": 33,
        "rating": 4.2,
        "reviews_count": 62,
        "tags": ["earbuds", "budget", "bass"],
    },
    {
        "id": 11,
        "name": "AirLoop Sport Earbuds",
        "description": "AirLoop's sport headphones deliver sweat resistant sound with a wireless build made for everyday listening.",
        "price": 54.99,
        "category": "Headphones",
        "brand": "AirLoop",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=11",
        "stock": 14,
        "rating": 3.7,
        "reviews_count": 115,
        "tags": ["sport", "sweat-resistant", "wireless"],
    },
    {
        "id": 12,
        "name": "QuietZone ANC Headset",
        "description": "QuietZone's noise cancelling headphones deliver travel sound with a foldable build made for everyday listening.",
        "price": 129.0,
        "category": "Headphones",
        "brand": "QuietZone",
        "image": "https://loremflickr.com/400/400/headphones,audio?lock=12",
        "stock": 11,
        "rating": 4.6,
        "reviews_count": 168,
        "tags": ["noise-cancelling", "travel", "foldable"],
    },
    {
        "id": 13,
        "name": "ChronoFit Fitness Watch",
        "description": "The ChronoFit smartwatch combines fitness tracking with heart rate features in a sleep tracking design.",
        "price": 129.0,
        "category": "Smart Watches",
        "brand": "ChronoFit",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=13",
        "stock": 20,
        "rating": 4.1,
        "reviews_count": 221,
        "tags": ["fitness", "heart-rate", "sleep-tracking"],
    },
    {
        "id": 14,
        "name": "PulseGuard Pro Watch",
        "description": "The PulseGuard smartwatch combines gps tracking with rugged features in a blood oxygen design.",
        "price": 189.99,
        "category": "Smart Watches",
        "brand": "PulseGuard",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=14",
        "stock": 9,
        "rating": 3.6,
        "reviews_count": 274,
        "tags": ["gps", "rugged", "blood-oxygen"],
    },
    {
        "id": 15,
        "name": "TimeSync Lite Watch",
        "description": "The TimeSync smartwatch combines budget tracking with notifications features in a battery life design.",
        "price": 69.99,
        "category": "Smart Watches",
        "brand": "TimeSync",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=15",
        "stock": 26,
        "rating": 4.5,
        "reviews_count": 327,
        "tags": ["budget", "notifications", "battery-life"],
    },
    {
        "id": 16,
        "name": "VitalTrack Health Watch",
        "description": "The VitalTrack smartwatch combines health tracking with ecg features in a premium design.",
        "price": 159.0,
        "category": "Smart Watches",
        "brand": "VitalTrack",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=16",
        "stock": 13,
        "rating": 4.0,
        "reviews_count": 380,
        "tags": ["health", "ecg", "premium"],
    },
    {
        "id": 17,
        "name": "OrbitWear Classic Watch",
        "description": "The OrbitWear smartwatch combines classic design tracking with notifications features in a everyday design.",
        "price": 99.5,
        "category": "Smart Watches",
        "brand": "OrbitWear",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=17",
        "stock": 15,
        "rating": 4.9,
        "reviews_count": 433,
        "tags": ["classic-design", "notifications", "everyday"],
    },
    {
        "id": 18,
        "name": "PeakPulse Adventure Watch",
        "description": "The PeakPulse smartwatch combines outdoor tracking with gps features in a rugged design.",
        "price": 219.0,
        "category": "Smart Watches",
        "brand": "PeakPulse",
        "image": "https://loremflickr.com/400/400/smartwatch,wearable?lock=18",
        "stock": 5,
        "rating": 4.4,
        "reviews_count": 486,
        "tags": ["outdoor", "gps", "rugged"],
    },
    {
        "id": 19,
        "name": "UrbanTrek 25L Daypack",
        "description": "A daily backpack designed for laptop sleeve use, with a water resistant build that holds up to daily wear.",
        "price": 54.99,
        "category": "Backpacks",
        "brand": "UrbanTrek",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=19",
        "stock": 30,
        "rating": 3.9,
        "reviews_count": 59,
        "tags": ["daily", "laptop-sleeve", "water-resistant"],
    },
    {
        "id": 20,
        "name": "SummitPack 40L Hiking Bag",
        "description": "A hiking backpack designed for large capacity use, with a rain cover build that holds up to daily wear.",
        "price": 89.0,
        "category": "Backpacks",
        "brand": "SummitPack",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=20",
        "stock": 7,
        "rating": 4.8,
        "reviews_count": 112,
        "tags": ["hiking", "large-capacity", "rain-cover"],
    },
    {
        "id": 21,
        "name": "CityGlide Slim Backpack",
        "description": "A commuter backpack designed for slim use, with a laptop sleeve build that holds up to daily wear.",
        "price": 44.99,
        "category": "Backpacks",
        "brand": "CityGlide",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=21",
        "stock": 24,
        "rating": 4.3,
        "reviews_count": 165,
        "tags": ["commuter", "slim", "laptop-sleeve"],
    },
    {
        "id": 22,
        "name": "VoyagePro Travel Backpack",
        "description": "A travel backpack designed for carry on use, with a expandable build that holds up to daily wear.",
        "price": 109.0,
        "category": "Backpacks",
        "brand": "VoyagePro",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=22",
        "stock": 10,
        "rating": 3.8,
        "reviews_count": 218,
        "tags": ["travel", "carry-on", "expandable"],
    },
    {
        "id": 23,
        "name": "CampusCarry Student Bag",
        "description": "A student backpack designed for budget use, with a everyday build that holds up to daily wear.",
        "price": 39.99,
        "category": "Backpacks",
        "brand": "CampusCarry",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=23",
        "stock": 40,
        "rating": 4.7,
        "reviews_count": 271,
        "tags": ["student", "budget", "everyday"],
    },
    {
        "id": 24,
        "name": "RidgeLine Tactical Pack",
        "description": "A tactical backpack designed for durable use, with a molle build that holds up to daily wear.",
        "price": 74.5,
        "category": "Backpacks",
        "brand": "RidgeLine",
        "image": "https://loremflickr.com/400/400/backpack,bag?lock=24",
        "stock": 16,
        "rating": 4.2,
        "reviews_count": 324,
        "tags": ["tactical", "durable", "molle"],
    },
    {
        "id": 25,
        "name": "EverSoft Classic Tee",
        "description": "A cotton t-shirt made from everyday fabric, cut for a relaxed fit everyday feel.",
        "price": 19.99,
        "category": "T-Shirts",
        "brand": "EverSoft",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=25",
        "stock": 50,
        "rating": 3.7,
        "reviews_count": 377,
        "tags": ["cotton", "everyday", "relaxed-fit"],
    },
    {
        "id": 26,
        "name": "FlexDry Athletic Tee",
        "description": "A moisture wicking t-shirt made from workout fabric, cut for a performance everyday feel.",
        "price": 24.99,
        "category": "T-Shirts",
        "brand": "FlexDry",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=26",
        "stock": 40,
        "rating": 4.6,
        "reviews_count": 430,
        "tags": ["moisture-wicking", "workout", "performance"],
    },
    {
        "id": 27,
        "name": "UrbanFit Graphic Tee",
        "description": "A graphic t-shirt made from streetwear fabric, cut for a casual everyday feel.",
        "price": 22.99,
        "category": "T-Shirts",
        "brand": "UrbanFit",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=27",
        "stock": 35,
        "rating": 4.1,
        "reviews_count": 483,
        "tags": ["graphic", "streetwear", "casual"],
    },
    {
        "id": 28,
        "name": "PureBlend Organic Tee",
        "description": "A organic t-shirt made from sustainable fabric, cut for a cotton everyday feel.",
        "price": 27.99,
        "category": "T-Shirts",
        "brand": "PureBlend",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=28",
        "stock": 20,
        "rating": 3.6,
        "reviews_count": 56,
        "tags": ["organic", "sustainable", "cotton"],
    },
    {
        "id": 29,
        "name": "CoolCore Breathable Tee",
        "description": "A breathable t-shirt made from summer fabric, cut for a lightweight everyday feel.",
        "price": 21.99,
        "category": "T-Shirts",
        "brand": "CoolCore",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=29",
        "stock": 28,
        "rating": 4.5,
        "reviews_count": 109,
        "tags": ["breathable", "summer", "lightweight"],
    },
    {
        "id": 30,
        "name": "BasicLayer V-Neck Tee",
        "description": "A basics t-shirt made from v neck fabric, cut for a everyday everyday feel.",
        "price": 18.99,
        "category": "T-Shirts",
        "brand": "BasicLayer",
        "image": "https://loremflickr.com/400/400/tshirt,apparel?lock=30",
        "stock": 45,
        "rating": 4.0,
        "reviews_count": 162,
        "tags": ["basics", "v-neck", "everyday"],
    },
    {
        "id": 31,
        "name": "RapidClick Pro Gaming Mouse",
        "description": "The RapidClick gaming mouse offers rgb tracking with programmable ergonomics and a high dpi feature set.",
        "price": 39.99,
        "category": "Gaming Mouse",
        "brand": "RapidClick",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=31",
        "stock": 22,
        "rating": 4.9,
        "reviews_count": 215,
        "tags": ["rgb", "programmable", "high-dpi"],
    },
    {
        "id": 32,
        "name": "NovaGrip Wireless Mouse",
        "description": "The NovaGrip gaming mouse offers wireless tracking with lightweight ergonomics and a esports feature set.",
        "price": 49.99,
        "category": "Gaming Mouse",
        "brand": "NovaGrip",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=32",
        "stock": 15,
        "rating": 4.4,
        "reviews_count": 268,
        "tags": ["wireless", "lightweight", "esports"],
    },
    {
        "id": 33,
        "name": "TitanGrip FPS Mouse",
        "description": "The TitanGrip gaming mouse offers fps tracking with high dpi ergonomics and a ergonomic feature set.",
        "price": 59.99,
        "category": "Gaming Mouse",
        "brand": "TitanGrip",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=33",
        "stock": 10,
        "rating": 3.9,
        "reviews_count": 321,
        "tags": ["fps", "high-dpi", "ergonomic"],
    },
    {
        "id": 34,
        "name": "ByteClick Budget Mouse",
        "description": "The ByteClick gaming mouse offers budget tracking with wired ergonomics and a everyday feature set.",
        "price": 19.99,
        "category": "Gaming Mouse",
        "brand": "ByteClick",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=34",
        "stock": 38,
        "rating": 4.8,
        "reviews_count": 374,
        "tags": ["budget", "wired", "everyday"],
    },
    {
        "id": 35,
        "name": "VortexAim MMO Mouse",
        "description": "The VortexAim gaming mouse offers mmo tracking with programmable ergonomics and a rgb feature set.",
        "price": 64.99,
        "category": "Gaming Mouse",
        "brand": "VortexAim",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=35",
        "stock": 8,
        "rating": 4.3,
        "reviews_count": 427,
        "tags": ["mmo", "programmable", "rgb"],
    },
    {
        "id": 36,
        "name": "SilentStrike Office Mouse",
        "description": "The SilentStrike gaming mouse offers silent click tracking with office ergonomics and a wireless feature set.",
        "price": 24.99,
        "category": "Gaming Mouse",
        "brand": "SilentStrike",
        "image": "https://loremflickr.com/400/400/gaming-mouse,computer-mouse?lock=36",
        "stock": 27,
        "rating": 3.8,
        "reviews_count": 480,
        "tags": ["silent-click", "office", "wireless"],
    },
    {
        "id": 37,
        "name": "KeyForge Mechanical Keyboard",
        "description": "A mechanical keyboard with hot swappable switches, built for rgb typing sessions.",
        "price": 89.99,
        "category": "Keyboard",
        "brand": "KeyForge",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=37",
        "stock": 14,
        "rating": 4.7,
        "reviews_count": 53,
        "tags": ["mechanical", "hot-swappable", "rgb"],
    },
    {
        "id": 38,
        "name": "SilentType 65% Keyboard",
        "description": "A compact keyboard with silent switches switches, built for travel typing sessions.",
        "price": 64.99,
        "category": "Keyboard",
        "brand": "SilentType",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=38",
        "stock": 0,
        "rating": 4.2,
        "reviews_count": 106,
        "tags": ["compact", "silent-switches", "travel"],
    },
    {
        "id": 39,
        "name": "ClickCraft Full-Size Board",
        "description": "A full size keyboard with tactile switches, built for office typing sessions.",
        "price": 74.99,
        "category": "Keyboard",
        "brand": "ClickCraft",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=39",
        "stock": 19,
        "rating": 3.7,
        "reviews_count": 159,
        "tags": ["full-size", "tactile", "office"],
    },
    {
        "id": 40,
        "name": "NeonBoard RGB Gaming Keyboard",
        "description": "A gaming keyboard with rgb switches, built for mechanical typing sessions.",
        "price": 109.0,
        "category": "Keyboard",
        "brand": "NeonBoard",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=40",
        "stock": 9,
        "rating": 4.6,
        "reviews_count": 212,
        "tags": ["gaming", "rgb", "mechanical"],
    },
    {
        "id": 41,
        "name": "WhisperKey Office Board",
        "description": "A office keyboard with quiet switches, built for budget typing sessions.",
        "price": 49.99,
        "category": "Keyboard",
        "brand": "WhisperKey",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=41",
        "stock": 31,
        "rating": 4.1,
        "reviews_count": 265,
        "tags": ["office", "quiet", "budget"],
    },
    {
        "id": 42,
        "name": "CompactForge 60% Keyboard",
        "description": "A compact keyboard with 60 percent switches, built for mechanical typing sessions.",
        "price": 79.99,
        "category": "Keyboard",
        "brand": "CompactForge",
        "image": "https://loremflickr.com/400/400/keyboard,mechanical-keyboard?lock=42",
        "stock": 12,
        "rating": 3.6,
        "reviews_count": 318,
        "tags": ["compact", "60-percent", "mechanical"],
    },
    {
        "id": 43,
        "name": "HorizonView Polarized Sunglasses",
        "description": "HorizonView sunglasses with polarized lenses and a uv400, titanium frame.",
        "price": 44.99,
        "category": "Sunglasses",
        "brand": "HorizonView",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=43",
        "stock": 27,
        "rating": 4.5,
        "reviews_count": 371,
        "tags": ["polarized", "uv400", "titanium"],
    },
    {
        "id": 44,
        "name": "DriftShade Sport Sunglasses",
        "description": "DriftShade sunglasses with sport lenses and a wraparound, anti slip frame.",
        "price": 34.99,
        "category": "Sunglasses",
        "brand": "DriftShade",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=44",
        "stock": 19,
        "rating": 4.0,
        "reviews_count": 424,
        "tags": ["sport", "wraparound", "anti-slip"],
    },
    {
        "id": 45,
        "name": "ClassicRim Aviator Sunglasses",
        "description": "ClassicRim sunglasses with aviator lenses and a classic, metal frame frame.",
        "price": 39.99,
        "category": "Sunglasses",
        "brand": "ClassicRim",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=45",
        "stock": 23,
        "rating": 4.9,
        "reviews_count": 477,
        "tags": ["aviator", "classic", "metal-frame"],
    },
    {
        "id": 46,
        "name": "UrbanTint Retro Sunglasses",
        "description": "UrbanTint sunglasses with retro lenses and a fashion, lightweight frame.",
        "price": 29.99,
        "category": "Sunglasses",
        "brand": "UrbanTint",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=46",
        "stock": 34,
        "rating": 4.4,
        "reviews_count": 50,
        "tags": ["retro", "fashion", "lightweight"],
    },
    {
        "id": 47,
        "name": "SolarPeak Hiking Sunglasses",
        "description": "SolarPeak sunglasses with outdoor lenses and a polarized, durable frame.",
        "price": 54.99,
        "category": "Sunglasses",
        "brand": "SolarPeak",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=47",
        "stock": 11,
        "rating": 3.9,
        "reviews_count": 103,
        "tags": ["outdoor", "polarized", "durable"],
    },
    {
        "id": 48,
        "name": "NightDrive Anti-Glare Sunglasses",
        "description": "NightDrive sunglasses with anti glare lenses and a driving, night frame.",
        "price": 32.99,
        "category": "Sunglasses",
        "brand": "NightDrive",
        "image": "https://loremflickr.com/400/400/sunglasses,eyewear?lock=48",
        "stock": 16,
        "rating": 4.8,
        "reviews_count": 156,
        "tags": ["anti-glare", "driving", "night"],
    },
]

# The in-memory cart. Key = product_id, Value = quantity.
# Example: {1: 2, 5: 1} means "2x product #1 and 1x product #5 in the cart".
CART: dict[int, int] = {}
